version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: deepest_learning
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build: .
    restart: unless-stopped
    env_file: .env
    command: flask run --host=0.0.0.0 --port=8000
    environment:
      FLASK_APP: run:app
      FLASK_ENV: development
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app

volumes:
  db_data:
