openapi: 3.0.0
info:
  title: Deepest Learning API
  version: "1.0.0"
  description: API for lecture instantiation, stepping and answering
paths:
  /instantiate-lecture:
    post:
      summary: Instantiate a lecture from a PDF + text
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                text:
                  type: string
      responses:
        '201':
          description: Lecture created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  message:
                    type: string
        '400':
          description: Bad request
  /step/{lecture_id}/{slide_num}:
    get:
      summary: Process a step (slide)
      parameters:
        - name: lecture_id
          in: path
          required: true
          schema:
            type: integer
        - name: slide_num
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: step result
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  slide:
                    type: integer
                  text:
                    type: string
        '404':
          description: slide not found
  /answer/{lecture_id}/{slide_num}:
    post:
      summary: Answer a question for a slide
      parameters:
        - name: lecture_id
          in: path
          required: true
          schema:
            type: integer
        - name: slide_num
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
      responses:
        '200':
          description: answer
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  slide:
                    type: integer
                  answer:
                    type: string
        '400':
          description: bad request
components: {}
